name: build_docker

on:
  push:
    branches:
      - master

jobs:
  bt-product-release: #构建docker并发布到阿里云容器镜像中
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # pull代码到运行服务器上

      - name: Build the Docker image
        env:
          IMAGE_TAG: ${{ github.sha }} # 用于标记容器版本号
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKERHUB_ALIYUN_USERNAME }} --password=${{ secrets.DOCKERHUB_ALIYUN_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/chenyue/plug-r-qw:$IMAGE_TAG
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/chenyue/plug-r-qw:$IMAGE_TAG
